sudo: false

language: ruby

cache: bundler

rvm:
  - 2.6.2

services:
  - xvfb
  - postgresql
  
before_script:
  - "cp config/database.travis.yml config/database.yml"
  - "RAILS_ENV=test bundle exec rake db:create"

